import Promise from "promise";

class Utility {
  constructor() {
    this.BASE_URL = "localhost:3000/";
    this.TimeZone = [
      { name: "Africa/Abidjan", abb: "GMT" },
      { name: "Africa/Accra", abb: "GMT" },
      { name: "Africa/Algiers", abb: "CET" },
      { name: "Africa/Bissau", abb: "GMT" },
      { name: "Africa/Cairo", abb: "EET" },
      { name: "Africa/Casablanca", abb: "ACT" },
      { name: "Africa/Ceuta", abb: "CET" },
      { name: "Africa/El_Aaiun", abb: "AEAT" },
      { name: "Africa/Johannesburg", abb: "SAST" },
      { name: "Africa/Juba", abb: "CAT" },
      { name: "Africa/Khartoum", abb: "CAT" },
      { name: "Africa/Lagos", abb: "WAT" },
      { name: "Africa/Maputo", abb: "CAT" },
      { name: "Africa/Monrovia", abb: "GMT" },
      { name: "Africa/Nairobi", abb: "EAT" },
      { name: "Africa/Ndjamena", abb: "WAT" },
      { name: "Africa/Sao_Tome", abb: "GMT" },
      { name: "Africa/Tripoli", abb: "EET" },
      { name: "Africa/Tunis", abb: "CET" },
      { name: "Africa/Windhoek", abb: "CAT" },
      { name: "America/Adak", abb: "HST" },
      { name: "America/Anchorage", abb: "AKST" },
      { name: "America/Araguaina", abb: "-03" },
      { name: "America/Argentina/Buenos_Aires", abb: "-03" },
      { name: "America/Argentina/Catamarca", abb: "-03" },
      { name: "America/Argentina/Cordoba", abb: "-03" },
      { name: "America/Argentina/Jujuy", abb: "-03" },
      { name: "America/Argentina/La_Rioja", abb: "-03" },
      { name: "America/Argentina/Mendoza", abb: "-03" },
      { name: "America/Argentina/Rio_Gallegos", abb: "-03" },
      { name: "America/Argentina/Salta", abb: "-03" },
      { name: "America/Argentina/San_Juan", abb: "-03" },
      { name: "America/Argentina/San_Luis", abb: "-03" },
      { name: "America/Argentina/Tucuman", abb: "-03" },
      { name: "America/Argentina/Ushuaia", abb: "-03" },
      { name: "America/Asuncion", abb: "-04" },
      { name: "America/Atikokan", abb: "EST" },
      { name: "America/Bahia", abb: "-03" },
      { name: "America/Bahia_Banderas", abb: "CST" },
      { name: "America/Barbados", abb: "AST" },
      { name: "America/Belem", abb: "-03" },
      { name: "America/Belize", abb: "CST" },
      { name: "America/Blanc-Sablon", abb: "AST" },
      { name: "America/Boa_Vista", abb: "-04" },
      { name: "America/Bogota", abb: "-05" },
      { name: "America/Boise", abb: "MST" },
      { name: "America/Cambridge_Bay", abb: "MDT" },
      { name: "America/Campo_Grande", abb: "-04" },
      { name: "America/Cancun", abb: "EST" },
      { name: "America/Caracas", abb: "-04" },
      { name: "America/Cayenne", abb: "-03" },
      { name: "America/Chicago", abb: "CST" },
      { name: "America/Chihuahua", abb: "MST" },
      { name: "America/Costa_Rica", abb: "CST" },
      { name: "America/Creston", abb: "MST" },
      { name: "America/Cuiaba", abb: "-04" },
      { name: "America/Curacao", abb: "AST" },
      { name: "America/Danmarkshavn", abb: "GMT" },
      { name: "America/Dawson", abb: "MST" },
      { name: "America/Dawson_Creek", abb: "MST" },
      { name: "America/Denver", abb: "MST" },
      { name: "America/Detroit", abb: "EST" },
      { name: "America/Edmonton", abb: "MST" },
      { name: "America/Eirunepe", abb: "-05" },
      { name: "America/El_Salvador", abb: "CST" },
      { name: "America/Fort_Nelson", abb: "MST" },
      { name: "America/Fortaleza", abb: "-03" },
      { name: "America/Glace_Bay", abb: "AST" },
      { name: "America/Goose_Bay", abb: "AST" },
      { name: "America/Grand_Turk", abb: "EST" },
      { name: "America/Guatemala", abb: "CST" },
      { name: "America/Guayaquil", abb: "-05" },
      { name: "America/Guyana", abb: "-04" },
      { name: "America/Halifax", abb: "AST" },
      { name: "America/Havana", abb: "CST" },
      { name: "America/Hermosillo", abb: "MST" },
      { name: "America/Indiana/Indianapolis", abb: "EST" },
      { name: "America/Indiana/Knox", abb: "CST" },
      { name: "America/Indiana/Marengo", abb: "EST" },
      { name: "America/Indiana/Petersburg", abb: "EST" },
      { name: "America/Indiana/Tell_City", abb: "CST" },
      { name: "America/Indiana/Vevay", abb: "EST" },
      { name: "America/Indiana/Vincennes", abb: "EST" },
      { name: "America/Indiana/Winamac", abb: "EST" },
      { name: "America/Inuvik", abb: "MST" },
      { name: "America/Iqaluit", abb: "EST" },
      { name: "America/Jamaica", abb: "EST" },
      { name: "America/Juneau", abb: "AKST" },
      { name: "America/Kentucky/Louisville", abb: "EST" },
      { name: "America/Kentucky/Monticello", abb: "EST" },
      { name: "America/La_Paz", abb: "-04" },
      { name: "America/Lima", abb: "-05" },
      { name: "America/Los_Angeles", abb: "PST" },
      { name: "America/Maceio", abb: "-03" },
      { name: "America/Managua", abb: "CST" },
      { name: "America/Manaus", abb: "-04" },
      { name: "America/Martinique", abb: "AST" },
      { name: "America/Matamoros", abb: "CST" },
      { name: "America/Mazatlan", abb: "MST" },
      { name: "America/Menominee", abb: "CST" },
      { name: "America/Merida", abb: "CST" },
      { name: "America/Metlakatla", abb: "AKST" },
      { name: "America/Mexico_City", abb: "CST" },
      { name: "America/Miquelon", abb: "-03" },
      { name: "America/Moncton", abb: "AST" },
      { name: "America/Monterrey", abb: "CST" },
      { name: "America/Montevideo", abb: "-03" },
      { name: "America/Nassau", abb: "EST" },
      { name: "America/New_York", abb: "EST" },
      { name: "America/Nipigon", abb: "EST" },
      { name: "America/Nome", abb: "AKST" },
      { name: "America/Noronha", abb: "-02" },
      { name: "America/North_Dakota/Beulah", abb: "CST" },
      { name: "America/North_Dakota/Center", abb: "CST" },
      { name: "America/North_Dakota/New_Salem", abb: "CST" },
      { name: "America/Nuuk", abb: "-03" },
      { name: "America/Ojinaga", abb: "MST" },
      { name: "America/Panama", abb: "EST" },
      { name: "America/Pangnirtung", abb: "EST" },
      { name: "America/Paramaribo", abb: "-03" },
      { name: "America/Phoenix", abb: "MST" },
      { name: "America/Port-au-Prince", abb: "EST" },
      { name: "America/Port_of_Spain", abb: "AST" },
      { name: "America/Porto_Velho", abb: "-04" },
      { name: "America/Puerto_Rico", abb: "AST" },
      { name: "America/Punta_Arenas", abb: "-03" },
      { name: "America/Rainy_River", abb: "CST" },
      { name: "America/Rankin_Inlet", abb: "CST" },
      { name: "America/Recife", abb: "-03" },
      { name: "America/Regina", abb: "CST" },
      { name: "America/Resolute", abb: "CST" },
      { name: "America/Rio_Branco", abb: "-05" },
      { name: "America/Santarem", abb: "-03" },
      { name: "America/Santiago", abb: "-04" },
      { name: "America/Santo_Domingo", abb: "AST" },
      { name: "America/Sao_Paulo", abb: "-03" },
      { name: "America/Scoresbysund", abb: "-01" },
      { name: "America/Sitka", abb: "AKST" },
      { name: "America/St_Johns", abb: "NST" },
      { name: "America/Swift_Current", abb: "CST" },
      { name: "America/Tegucigalpa", abb: "CST" },
      { name: "America/Thule", abb: "AST" },
      { name: "America/Thunder_Bay", abb: "EST" },
      { name: "America/Tijuana", abb: "PST" },
      { name: "America/Toronto", abb: "EST" },
      { name: "America/Vancouver", abb: "PST" },
      { name: "America/Whitehorse", abb: "MST" },
      { name: "America/Winnipeg", abb: "CST" },
      { name: "America/Yakutat", abb: "AKST" },
      { name: "America/Yellowknife", abb: "MST" },
      { name: "Antarctica/Casey", abb: "+11" },
      { name: "Antarctica/Davis", abb: "+07" },
      { name: "Antarctica/DumontDUrville", abb: "+10" },
      { name: "Antarctica/Macquarie", abb: "AEST" },
      { name: "Antarctica/Mawson", abb: "+05" },
      { name: "Antarctica/Palmer", abb: "-03" },
      { name: "Antarctica/Rothera", abb: "-03" },
      { name: "Antarctica/Syowa", abb: "+03" },
      { name: "Antarctica/Troll", abb: "+00" },
      { name: "Antarctica/Vostok", abb: "+06" },
      { name: "Asia/Almaty", abb: "+06" },
      { name: "Asia/Amman", abb: "EET" },
      { name: "Asia/Anadyr", abb: "+12" },
      { name: "Asia/Aqtau", abb: "+05" },
      { name: "Asia/Aqtobe", abb: "+05" },
      { name: "Asia/Ashgabat", abb: "+05" },
      { name: "Asia/Atyrau", abb: "+05" },
      { name: "Asia/Baghdad", abb: "+03" },
      { name: "Asia/Baku", abb: "+04" },
      { name: "Asia/Bangkok", abb: "+07" },
      { name: "Asia/Barnaul", abb: "+07" },
      { name: "Asia/Beirut", abb: "EET" },
      { name: "Asia/Bishkek", abb: "+06" },
      { name: "Asia/Brunei", abb: "+08" },
      { name: "Asia/Chita", abb: "+09" },
      { name: "Asia/Choibalsan", abb: "+08" },
      { name: "Asia/Colombo", abb: "+0530" },
      { name: "Asia/Damascus", abb: "EET" },
      { name: "Asia/Dhaka", abb: "+06" },
      { name: "Asia/Dili", abb: "+09" },
      { name: "Asia/Dubai", abb: "+04" },
      { name: "Asia/Dushanbe", abb: "+05" },
      { name: "Asia/Famagusta", abb: "EET" },
      { name: "Asia/Gaza", abb: "EET" },
      { name: "Asia/Hebron", abb: "EET" },
      { name: "Asia/Ho_Chi_Minh", abb: "+07" },
      { name: "Asia/Hong_Kong", abb: "HKT" },
      { name: "Asia/Hovd", abb: "+07" },
      { name: "Asia/Irkutsk", abb: "+08" },
      { name: "Asia/Jakarta", abb: "WIB" },
      { name: "Asia/Jayapura", abb: "WIT" },
      { name: "Asia/Jerusalem", abb: "IST" },
      { name: "Asia/Kabul", abb: "+0430" },
      { name: "Asia/Kamchatka", abb: "+12" },
      { name: "Asia/Karachi", abb: "PKT" },
      { name: "Asia/Kathmandu", abb: "+0545" },
      { name: "Asia/Khandyga", abb: "+09" },
      { name: "Asia/Kolkata", abb: "IST" },
      { name: "Asia/Krasnoyarsk", abb: "+07" },
      { name: "Asia/Kuala_Lumpur", abb: "+08" },
      { name: "Asia/Kuching", abb: "+08" },
      { name: "Asia/Macau", abb: "CST" },
      { name: "Asia/Magadan", abb: "+11" },
      { name: "Asia/Makassar", abb: "WITA" },
      { name: "Asia/Manila", abb: "PST" },
      { name: "Asia/Nicosia", abb: "EET" },
      { name: "Asia/Novokuznetsk", abb: "+07" },
      { name: "Asia/Novosibirsk", abb: "+07" },
      { name: "Asia/Omsk", abb: "+06" },
      { name: "Asia/Oral", abb: "+05" },
      { name: "Asia/Pontianak", abb: "WIB" },
      { name: "Asia/Pyongyang", abb: "KST" },
      { name: "Asia/Qatar", abb: "+03" },
      { name: "Asia/Qostanay", abb: "+06" },
      { name: "Asia/Qyzylorda", abb: "+05" },
      { name: "Asia/Riyadh", abb: "+03" },
      { name: "Asia/Sakhalin", abb: "+11" },
      { name: "Asia/Samarkand", abb: "+05" },
      { name: "Asia/Seoul", abb: "KST" },
      { name: "Asia/Shanghai", abb: "CST" },
      { name: "Asia/Singapore", abb: "+08" },
      { name: "Asia/Srednekolymsk", abb: "+11" },
      { name: "Asia/Taipei", abb: "CST" },
      { name: "Asia/Tashkent", abb: "+05" },
      { name: "Asia/Tbilisi", abb: "+04" },
      { name: "Asia/Tehran", abb: "+0330" },
      { name: "Asia/Thimphu", abb: "+06" },
      { name: "Asia/Tokyo", abb: "JST" },
      { name: "Asia/Tomsk", abb: "+07" },
      { name: "Asia/Ulaanbaatar", abb: "+08" },
      { name: "Asia/Urumqi", abb: "+06" },
      { name: "Asia/Ust-Nera", abb: "+10" },
      { name: "Asia/Vladivostok", abb: "+10" },
      { name: "Asia/Yakutsk", abb: "+09" },
      { name: "Asia/Yangon", abb: "+0630" },
      { name: "Asia/Yekaterinburg", abb: "+05" },
      { name: "Asia/Yerevan", abb: "+04" },
      { name: "Atlantic/Azores", abb: "-01" },
      { name: "Atlantic/Bermuda", abb: "AST" },
      { name: "Atlantic/Canary", abb: "WET" },
      { name: "Atlantic/Cape_Verde", abb: "-01" },
      { name: "Atlantic/Faroe", abb: "WET" },
      { name: "Atlantic/Madeira", abb: "WET" },
      { name: "Atlantic/Reykjavik", abb: "GMT" },
      { name: "Atlantic/South_Georgia", abb: "-02" },
      { name: "Atlantic/Stanley", abb: "-03" },
      { name: "Australia/Adelaide", abb: "ACST" },
      { name: "Australia/Brisbane", abb: "AEST" },
      { name: "Australia/Broken_Hill", abb: "ACST" },
      { name: "Australia/Darwin", abb: "ACST" },
      { name: "Australia/Eucla", abb: "+0845" },
      { name: "Australia/Hobart", abb: "AEST" },
      { name: "Australia/Lindeman", abb: "AEST" },
      { name: "Australia/Lord_Howe", abb: "+1030" },
      { name: "Australia/Melbourne", abb: "AEST" },
      { name: "Australia/Perth", abb: "AWST" },
      { name: "Australia/Sydney", abb: "AEST" },
      { name: "CET", abb: "CET" },
      { name: "CST6CDT", abb: "CST" },
      { name: "EET", abb: "EET" },
      { name: "EST", abb: "EST" },
      { name: "EST5EDT", abb: "EST" },
      { name: "Etc/GMT", abb: "GMT" },
      { name: "Etc/GMT+1", abb: "-01" },
      { name: "Etc/GMT+10", abb: "-10" },
      { name: "Etc/GMT+11", abb: "-11" },
      { name: "Etc/GMT+12", abb: "-12" },
      { name: "Etc/GMT+2", abb: "-02" },
      { name: "Etc/GMT+3", abb: "-03" },
      { name: "Etc/GMT+4", abb: "-04" },
      { name: "Etc/GMT+5", abb: "-05" },
      { name: "Etc/GMT+6", abb: "-06" },
      { name: "Etc/GMT+7", abb: "-07" },
      { name: "Etc/GMT+8", abb: "-08" },
      { name: "Etc/GMT+9", abb: "-09" },
      { name: "Etc/GMT-1", abb: "+01" },
      { name: "Etc/GMT-10", abb: "+10" },
      { name: "Etc/GMT-11", abb: "+11" },
      { name: "Etc/GMT-12", abb: "+12" },
      { name: "Etc/GMT-13", abb: "+13" },
      { name: "Etc/GMT-14", abb: "+14" },
      { name: "Etc/GMT-2", abb: "+02" },
      { name: "Etc/GMT-3", abb: "+03" },
      { name: "Etc/GMT-4", abb: "+04" },
      { name: "Etc/GMT-5", abb: "+05" },
      { name: "Etc/GMT-6", abb: "+06" },
      { name: "Etc/GMT-7", abb: "+07" },
      { name: "Etc/GMT-8", abb: "+08" },
      { name: "Etc/GMT-9", abb: "+09" },
      { name: "Etc/UTC", abb: "UTC" },
      { name: "Europe/Amsterdam", abb: "CET" },
      { name: "Europe/Andorra", abb: "CET" },
      { name: "Europe/Astrakhan", abb: "+04" },
      { name: "Europe/Athens", abb: "EET" },
      { name: "Europe/Belgrade", abb: "CET" },
      { name: "Europe/Berlin", abb: "CET" },
      { name: "Europe/Brussels", abb: "CET" },
      { name: "Europe/Bucharest", abb: "EET" },
      { name: "Europe/Budapest", abb: "CET" },
      { name: "Europe/Chisinau", abb: "EET" },
      { name: "Europe/Copenhagen", abb: "CET" },
      { name: "Europe/Dublin", abb: "IST" },
      { name: "Europe/Gibraltar", abb: "CET" },
      { name: "Europe/Helsinki", abb: "EET" },
      { name: "Europe/Istanbul", abb: "+03" },
      { name: "Europe/Kaliningrad", abb: "EET" },
      { name: "Europe/Kiev", abb: "EET" },
      { name: "Europe/Kirov", abb: "+03" },
      { name: "Europe/Lisbon", abb: "WET" },
      { name: "Europe/London", abb: "GMT" },
      { name: "Europe/Luxembourg", abb: "CET" },
      { name: "Europe/Madrid", abb: "CET" },
      { name: "Europe/Malta", abb: "CET" },
      { name: "Europe/Minsk", abb: "+03" },
      { name: "Europe/Monaco", abb: "CET" },
      { name: "Europe/Moscow", abb: "MSK" },
      { name: "Europe/Oslo", abb: "CET" },
      { name: "Europe/Paris", abb: "CET" },
      { name: "Europe/Prague", abb: "CET" },
      { name: "Europe/Riga", abb: "EET" },
      { name: "Europe/Rome", abb: "CET" },
      { name: "Europe/Samara", abb: "+04" },
      { name: "Europe/Saratov", abb: "+04" },
      { name: "Europe/Simferopol", abb: "MSK" },
      { name: "Europe/Sofia", abb: "EET" },
      { name: "Europe/Stockholm", abb: "CET" },
      { name: "Europe/Tallinn", abb: "EET" },
      { name: "Europe/Tirane", abb: "CET" },
      { name: "Europe/Ulyanovsk", abb: "+04" },
      { name: "Europe/Uzhgorod", abb: "EET" },
      { name: "Europe/Vienna", abb: "CET" },
      { name: "Europe/Vilnius", abb: "EET" },
      { name: "Europe/Volgograd", abb: "+03" },
      { name: "Europe/Warsaw", abb: "CET" },
      { name: "Europe/Zaporozhye", abb: "EET" },
      { name: "Europe/Zurich", abb: "CET" },
      { name: "HST", abb: "HST" },
      { name: "Indian/Chagos", abb: "+06" },
      { name: "Indian/Christmas", abb: "+07" },
      { name: "Indian/Cocos", abb: "+0630" },
      { name: "Indian/Kerguelen", abb: "+05" },
      { name: "Indian/Mahe", abb: "+04" },
      { name: "Indian/Maldives", abb: "+05" },
      { name: "Indian/Mauritius", abb: "+04" },
      { name: "Indian/Reunion", abb: "+04" },
      { name: "MET", abb: "MET" },
      { name: "MST", abb: "MST" },
      { name: "MST7MDT", abb: "MST" },
      { name: "PST8PDT", abb: "PST" },
      { name: "Pacific/Apia", abb: "+13" },
      { name: "Pacific/Auckland", abb: "NZST" },
      { name: "Pacific/Bougainville", abb: "+11" },
      { name: "Pacific/Chatham", abb: "+1245" },
      { name: "Pacific/Chuuk", abb: "+10" },
      { name: "Pacific/Easter", abb: "-06" },
      { name: "Pacific/Efate", abb: "+11" },
      { name: "Pacific/Enderbury", abb: "+13" },
      { name: "Pacific/Fakaofo", abb: "+13" },
      { name: "Pacific/Fiji", abb: "+12" },
      { name: "Pacific/Funafuti", abb: "+12" },
      { name: "Pacific/Galapagos", abb: "-06" },
      { name: "Pacific/Gambier", abb: "-09" },
      { name: "Pacific/Guadalcanal", abb: "+11" },
      { name: "Pacific/Guam", abb: "ChST" },
      { name: "Pacific/Honolulu", abb: "HST" },
      { name: "Pacific/Kiritimati", abb: "+14" },
      { name: "Pacific/Kosrae", abb: "+11" },
      { name: "Pacific/Kwajalein", abb: "+12" },
      { name: "Pacific/Majuro", abb: "+12" },
      { name: "Pacific/Marquesas", abb: "-0930" },
      { name: "Pacific/Nauru", abb: "+12" },
      { name: "Pacific/Niue", abb: "-11" },
      { name: "Pacific/Norfolk", abb: "+11" },
      { name: "Pacific/Noumea", abb: "+11" },
      { name: "Pacific/Pago_Pago", abb: "SST" },
      { name: "Pacific/Palau", abb: "+09" },
      { name: "Pacific/Pitcairn", abb: "-08" },
      { name: "Pacific/Pohnpei", abb: "+11" },
      { name: "Pacific/Port_Moresby", abb: "+10" },
      { name: "Pacific/Rarotonga", abb: "-10" },
      { name: "Pacific/Tahiti", abb: "-10" },
      { name: "Pacific/Tarawa", abb: "+12" },
      { name: "Pacific/Tongatapu", abb: "+13" },
      { name: "Pacific/Wake", abb: "+12" },
      { name: "Pacific/Wallis", abb: "+12" },
      { name: "WET", abb: "WET" },
    ];
  }

  convertBase64(file) {
    return new Promise((resolve, reject) => {
      const fileReader = new FileReader();
      fileReader.readAsDataURL(file);

      fileReader.onload = () => {
        resolve(fileReader.result);
      };

      fileReader.onerror = (error) => {
        reject(error);
      };
    });
  }

  //   handleError(error, errorCallBack) {
  //     console.log("error-code: ", error.code);
  //     if (!isNaN(error.code)) {
  //       if (parseInt(error.code) === 301) {
  //         console.log("response-301-detected");
  //         localStorage.removeItem("info");
  //         Cookies.remove("info");
  //         Cookies.remove("token");
  //         Cookies.remove("userType");
  //         Cookies.remove("uid");
  //         errorCallBack("Please reload this page.");
  //       } else {
  //         if (error.hasOwnProperty("messages")) {
  //           let message = "";
  //           error.messages.map((msg) => {
  //             message = message + " " + msg;
  //           });

  //           errorCallBack(message);
  //         } else {
  //           errorCallBack(error.message);
  //         }
  //       }
  //     } else {
  //       if (error.response) {
  //         if (error.response.data.hasOwnProperty("messages")) {
  //           let message = "";
  //           error.response.data.messages.map((msg) => {
  //             message = message + " " + msg;
  //           });

  //           errorCallBack(message);
  //         } else if (error.response.data.message) {
  //           errorCallBack(
  //             "Error: " +
  //               "Code " +
  //               error.response.status +
  //               " " +
  //               error.response.data.message
  //           );
  //         } else if (error.response.data.errors) {
  //           errorCallBack("Error: " + error.response.data.errors[0]);
  //         }
  //       } else if (error.request) {
  //         errorCallBack("Error: " + error.request);
  //       } else {
  //         errorCallBack("Error: " + error.message);
  //       }
  //     }
  //   }

  //   insertAtIndex(str, substring, index) {
  //     return str.slice(0, index) + substring + str.slice(index);
  //   }

  //   classNames(...classes) {
  //     return classes.filter(Boolean).join(" ");
  //   }
}
const utility = new Utility();
export default utility;
